# -*- coding: utf-8 -*-
"""app_mac.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1viylYlYQA4N26fgAEpvcR98VBpng3-NH
"""

import json
from io import BytesIO
from datetime import datetime

import matplotlib.pyplot as plt
import pandas as pd
import streamlit as st
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter


# =========================================================
# CONFIGURACIÓN DE LA PÁGINA
# =========================================================
st.set_page_config(
    page_title="Calculadora de Pensión Pro",
    page_icon="📊",
    layout="wide"
)


# =========================================================
# ESTADO INICIAL
# =========================================================
def inicializar_estado():
    defaults = {
    "interes_anual": 6.0,
    "capital_inicial": 0.0,
    "aporte_mensual": 150.0,
    "subida_anual_aportes": 2.0,
    "aporte_extra_anual": 200.0,
    "años_inversion": 30,
    "inflacion_estimada": 3.0,
    "impuestos_rescate": 19.0,
    "ingresos_mensuales": 0.0,

    "acad_monto": 100.0,
    "acad_infla": 3.0,
    "acad_años": 20,

    "fiscal_capital_inicial": 10000.0,
    "fiscal_aporte_anual": 2400.0,
    "fiscal_años": 25,
    "fiscal_rentabilidad": 7.0,
    "fiscal_impuesto": 19.0,
    "fiscal_rotacion": 20.0,

    "libertad_objetivo": 1500.0,
    "libertad_max_años": 60,

    "ultima_simulacion": None,
    "estado_simulacion": "Todavía no hay ninguna simulación calculada.",

    "rentabilidad_pendiente": None,
    "mensaje_rentabilidad_copiada": "",

    "comp_a_nombre": "Plan A",
    "comp_a_interes_anual": 6.0,
    "comp_a_capital_inicial": 0.0,
    "comp_a_aporte_mensual": 150.0,
    "comp_a_subida_anual_aportes": 2.0,
    "comp_a_aporte_extra_anual": 200.0,
    "comp_a_años_inversion": 30,
    "comp_a_inflacion_estimada": 3.0,
    "comp_a_impuestos_rescate": 19.0,
    "comp_a_ingresos_mensuales": 0.0,

    "comp_b_nombre": "Plan B",
    "comp_b_interes_anual": 8.0,
    "comp_b_capital_inicial": 0.0,
    "comp_b_aporte_mensual": 250.0,
    "comp_b_subida_anual_aportes": 2.0,
    "comp_b_aporte_extra_anual": 500.0,
    "comp_b_años_inversion": 30,
    "comp_b_inflacion_estimada": 3.0,
    "comp_b_impuestos_rescate": 19.0,
    "comp_b_ingresos_mensuales": 0.0,
}

    for k, v in defaults.items():
        if k not in st.session_state:
            st.session_state[k] = v


inicializar_estado()

if st.session_state.get("rentabilidad_pendiente") is not None:
    st.session_state["interes_anual"] = float(st.session_state["rentabilidad_pendiente"])
    st.session_state["mensaje_rentabilidad_copiada"] = (
        f"Se ha copiado {st.session_state['rentabilidad_pendiente']}% "
        f"al campo de interés anual esperado del plan principal."
    )
    st.session_state["rentabilidad_pendiente"] = None


# =========================================================
# AYUDAS
# =========================================================
AYUDAS_ENTRADAS = {
    "int": {
        "titulo": "Interés anual esperado (%)",
        "texto": (
            "Es la rentabilidad media anual que esperas obtener de tus inversiones.\n\n"
            "No significa que cada año vayas a ganar exactamente eso. Un año puedes ganar 12%, "
            "otro perder 8%, y a largo plazo promediar, por ejemplo, 6%.\n\n"
            "Ejemplo:\n"
            "- Si inviertes 10.000€ al 6% anual, al cabo de 1 año tendrías unos 10.600€.\n"
            "- Si además sigues aportando dinero, el crecimiento será mayor gracias al interés compuesto.\n\n"
            "Valores orientativos:\n"
            "- 3% a 5%: perfil prudente\n"
            "- 6% a 8%: cartera diversificada\n"
            "- 9% o más: hipótesis agresiva"
        )
    },
    "cap": {
        "titulo": "Capital inicial (€)",
        "texto": (
            "Es el dinero que ya tienes hoy y que incluyes en el plan desde el primer día.\n\n"
            "Ejemplo:\n"
            "- Si ya tienes 15.000€ invertidos, aquí pondrías 15000.\n"
            "- Si empiezas desde cero, escribe 0.\n\n"
            "Ese dinero empieza a trabajar desde el mes 1."
        )
    },
    "mensual": {
        "titulo": "Aporte mensual (€)",
        "texto": (
            "Es la cantidad fija que añades cada mes a tu inversión.\n\n"
            "Ejemplo:\n"
            "- Si apartas 250€ al mes de tu nómina, aquí debes poner 250.\n\n"
            "Es una de las variables más potentes porque actúa todos los meses y se acumula durante años."
        )
    },
    "inc": {
        "titulo": "Subida anual de aportes (%)",
        "texto": (
            "Es el porcentaje en el que aumentas tus aportaciones cada año.\n\n"
            "Sirve para simular que, con el tiempo, mejoras tu capacidad de ahorro.\n\n"
            "Ejemplo:\n"
            "- Empiezas con 200€/mes.\n"
            "- Si subes un 3% anual, el segundo año aportarías 206€/mes.\n"
            "- El tercer año, 212,18€/mes.\n\n"
            "Esto hace el plan más realista y más potente."
        )
    },
    "extra": {
        "titulo": "Aporte extra anual (€)",
        "texto": (
            "Es una cantidad adicional que añades una vez al año.\n\n"
            "Ejemplo:\n"
            "- Si cada Navidad inviertes 1.000€ de la paga extra, aquí pondrías 1000.\n"
            "- Si no haces aportes extra, pon 0.\n\n"
            "A largo plazo, estas inyecciones tienen mucho impacto."
        )
    },
    "años": {
        "titulo": "Años de inversión",
        "texto": (
            "Es el número de años que vas a mantener el plan antes de rescatar el dinero.\n\n"
            "Ejemplo:\n"
            "- Si tienes 35 años y te jubilarás a los 65, aquí pondrías 30.\n\n"
            "Cuanto más largo el plazo, más fuerte se vuelve el interés compuesto."
        )
    },
    "infla": {
        "titulo": "Inflación estimada (%)",
        "texto": (
            "La inflación es la subida general de precios con el paso del tiempo.\n\n"
            "Sirve para traducir el dinero futuro a 'euros de hoy'.\n\n"
            "Ejemplo:\n"
            "- Algo que hoy cuesta 100€ puede costar 180€ dentro de muchos años.\n\n"
            "Por eso esta app muestra tanto el valor nominal como el valor real."
        )
    },
    "tax": {
        "titulo": "Impuestos al rescate (%)",
        "texto": (
            "Es el porcentaje que estimas pagar sobre los beneficios al retirar el dinero.\n\n"
            "En esta simulación se aplica solo sobre la ganancia, no sobre lo aportado por ti.\n\n"
            "Ejemplo:\n"
            "- Aportas 50.000€\n"
            "- Acabas con 80.000€\n"
            "- Beneficio: 30.000€\n"
            "- Con un 19%, pagarías 5.700€"
        )
    },
    "ingresos": {
        "titulo": "Ingresos mensuales (€)",
        "texto": (
            "Es tu sueldo o ingreso mensual neto aproximado.\n\n"
            "No afecta al crecimiento de la cartera, pero sirve para calcular tu tasa de ahorro.\n\n"
            "Ejemplo:\n"
            "- Si cobras 1.800€ al mes y ahorras 300€, tu tasa de ahorro ronda el 16,7%.\n\n"
            "También permite añadir la columna de tasa de ahorro en el Excel."
        )
    }
}

AYUDAS_SALIDA = {
    "total_aportado": (
        "Es la suma de todo el dinero que has puesto tú durante el plan:\n"
        "capital inicial + aportes mensuales + aportes extra.\n\n"
        "No incluye las ganancias del mercado."
    ),
    "capital_bruto": (
        "Es el dinero total acumulado al final antes de descontar impuestos.\n\n"
        "Incluye tus aportaciones y todo lo generado por la inversión."
    ),
    "beneficio_bruto": (
        "Es la parte del capital que no has puesto tú directamente.\n\n"
        "Se calcula como:\n"
        "capital bruto - total aportado"
    ),
    "impuestos": (
        "Es la estimación de lo que pagarías sobre los beneficios al retirar el dinero.\n\n"
        "En esta app se aplica sobre la ganancia acumulada."
    ),
    "neto_final": (
        "Es el capital que te quedaría realmente después de restar impuestos.\n\n"
        "Es la cifra más útil para planificar lo que de verdad tendrías disponible."
    ),
    "valor_real_hoy": (
        "Es el poder adquisitivo del capital neto expresado en euros de hoy.\n\n"
        "Sirve para no engañarte con cifras futuras que parecen grandes pero comprarán menos."
    ),
    "pension_vitalicia": (
        "Es una estimación mensual basada en la regla del 4%.\n\n"
        "Fórmula:\n"
        "(capital neto × 0.04) / 12"
    ),
    "pension_real": (
        "Es la pensión mensual estimada por la regla del 4%, pero expresada en euros de hoy."
    ),
    "tasa_ahorro": (
        "Es el porcentaje de tus ingresos que estás destinando al ahorro e inversión.\n\n"
        "Aquí se calcula usando:\n"
        "(aporte mensual + extra anual/12) / ingresos mensuales × 100"
    ),
    "score_ahorro": (
        "Es una valoración orientativa de tu disciplina de ahorro.\n\n"
        "No es una medida oficial, pero sirve para darte contexto:\n"
        "- menos del 10%: baja\n"
        "- 10% a 20%: decente\n"
        "- 20% a 35%: fuerte\n"
        "- más del 35%: muy fuerte"
    )
}

GUIA_COLUMNAS_EXCEL = {
    "Año": "Número de año dentro de la simulación.",
    "Mes": "Número de mes dentro del año.",
    "Meses invirtiendo": "Tiempo total acumulado en meses desde el inicio.",
    "Años invirtiendo": "Tiempo total acumulado expresado en años.",
    "Capital inicial del mes": "Capital con el que arrancas ese mes antes de aportar ni rentar.",
    "Aporte mensual": "Cantidad que introduces ese mes.",
    "Aporte extra en este mes": "Aporte extraordinario. Normalmente aparece en el mes 12.",
    "Aportado acumulado": "Todo lo que tú has puesto hasta ese momento.",
    "Interés generado este mes": "Ganancia financiera creada ese mes por la cartera.",
    "Resultado acumulado bruto": "Capital total nominal menos aportado acumulado. Puede ser negativo si la cartera va mal.",
    "Capital total nominal": "Valor total de la cartera en euros futuros, sin descontar inflación.",
    "Índice inflación acumulada": "Factor acumulado de inflación desde el inicio.",
    "Capital total real (euros de hoy)": "Valor de la cartera medido en poder adquisitivo actual.",
    "Pérdida por inflación": "Diferencia entre capital nominal y capital real.",
    "Rendimiento vs Aportes (%)": "Qué parte del capital total procede de la rentabilidad y no de tu bolsillo.",
    "Impuestos estimados si rescataras aquí": "Impuesto estimado si vendieras y retiraras todo en ese momento.",
    "Capital neto estimado": "Capital después de impuestos estimados.",
    "Capital neto real estimado": "Capital neto, pero expresado en euros de hoy.",
    "Retirada mensual segura (Regla 4%)": "Pensión mensual estimada aplicando la regla del 4%.",
    "Aporte mensual vigente": "Aporte mensual que estaba activo en ese momento.",
    "Aporte extra anual vigente": "Aporte anual extra vigente en ese momento.",
    "Tasa de ahorro anualizada (%)": "Porcentaje de ingresos destinado al ahorro, si has informado tus ingresos mensuales.",
    "Capital inicio de año": "Capital con el que empieza ese año.",
    "Aportado en el año": "Todo lo que has aportado en ese año.",
    "Interés generado en el año": "Rentabilidad total obtenida ese año.",
    "Capital antes del extra anual": "Capital justo antes de sumar el aporte extra anual.",
    "Capital total nominal fin de año": "Valor nominal de la cartera al cierre del año.",
    "Capital total real fin de año": "Valor real de la cartera al cierre del año.",
    "Beneficio bruto acumulado": "Ganancia acumulada total antes de impuestos.",
    "Impuestos estimados si rescataras ese año": "Impuesto estimado si retiraras todo al final de ese año.",
    "Capital neto estimado fin de año": "Capital neto disponible a final de año.",
    "Capital neto real fin de año": "Capital neto final de año en euros de hoy.",
    "Pensión mensual estimada (regla 4%)": "Retirada mensual teórica en euros nominales.",
    "Pensión mensual real estimada": "Retirada mensual teórica en euros de hoy."
}

ACTIVOS = [
    ("S&P 500", "10.0", "Alta", "Renta variable USA. Orientativo a muy largo plazo."),
    ("Bonos globales", "4.0", "Baja/Media", "Más estabilidad, menor retorno esperado."),
    ("Oro", "7.0", "Media", "Activo defensivo, no produce flujo, pero sirve de diversificador."),
    ("Cartera 60/40", "7.0", "Media", "Mezcla clásica de acciones y bonos."),
    ("Cuenta remunerada / monetario", "2.5", "Baja", "Muy conservador, útil para liquidez."),
    ("Inmobiliario global", "6.0", "Media", "Orientativo, depende mucho del vehículo."),
    ("Nasdaq 100", "12.0", "Muy alta", "Más crecimiento potencial, también más volatilidad.")
]


# =========================================================
# UTILIDADES
# =========================================================
def formatear_euros(valor):
    return f"{valor:,.2f} €".replace(",", "X").replace(".", ",").replace("X", ".")

def formatear_pct(valor):
    return f"{valor:,.2f}%".replace(",", "X").replace(".", ",").replace("X", ".")

def ajustar_ancho_columnas(ws):
    for col in ws.columns:
        max_length = 0
        col_letter = get_column_letter(col[0].column)
        for cell in col:
            try:
                valor = str(cell.value) if cell.value is not None else ""
                if len(valor) > max_length:
                    max_length = len(valor)
            except Exception:
                pass
        ws.column_dimensions[col_letter].width = min(max_length + 2, 28)

def score_tasa_ahorro(tasa):
    if tasa is None:
        return "No calculable"
    if tasa < 10:
        return "Baja"
    if tasa < 20:
        return "Decente"
    if tasa < 35:
        return "Fuerte"
    return "Muy fuerte"

def aplicar_formato_excel(ws):
    dinero_keywords = [
        "Capital", "Aporte", "Interés", "Impuestos", "Pensión",
        "Retirada", "Beneficio", "Resultado", "Pérdida"
    ]
    porcentaje_keywords = ["%", "Tasa", "Rendimiento vs Aportes"]

    ws.freeze_panes = "A2"
    ws.auto_filter.ref = ws.dimensions

    for cell in ws[1]:
        cell.fill = PatternFill("solid", fgColor="1F4E78")
        cell.font = Font(color="FFFFFF", bold=True)
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

    for col_idx, cell in enumerate(ws[1], start=1):
        header = str(cell.value)

        for row in range(2, ws.max_row + 1):
            c = ws.cell(row=row, column=col_idx)
            if isinstance(c.value, (int, float)):
                if any(k in header for k in porcentaje_keywords):
                    c.number_format = "0.00"
                elif any(k in header for k in dinero_keywords):
                    c.number_format = "#,##0.00"
                else:
                    c.number_format = "0.0000"

    ajustar_ancho_columnas(ws)

def obtener_tasa_ahorro_actual(mensual, extra, ingresos_mensuales):
    if ingresos_mensuales <= 0:
        return None
    return ((mensual + (extra / 12)) / ingresos_mensuales) * 100


# =========================================================
# LECTURA DE ENTRADAS
# =========================================================
def leer_entradas_principales():
    tasa_anual = st.session_state["interes_anual"] / 100
    cap_inicial = st.session_state["capital_inicial"]
    mensual = st.session_state["aporte_mensual"]
    extra = st.session_state["aporte_extra_anual"]
    años = int(st.session_state["años_inversion"])
    inflacion_tasa = st.session_state["inflacion_estimada"] / 100
    impuesto_pct = st.session_state["impuestos_rescate"] / 100
    incremento_anual = st.session_state["subida_anual_aportes"] / 100
    ingresos_mensuales = st.session_state["ingresos_mensuales"]

    if años <= 0:
        raise ValueError("Los años deben ser mayores que 0.")
    if cap_inicial < 0 or mensual < 0 or extra < 0 or ingresos_mensuales < 0:
        raise ValueError("No se admiten cantidades negativas.")
    if tasa_anual <= -1 or inflacion_tasa <= -1 or impuesto_pct < 0:
        raise ValueError("Revisa los porcentajes introducidos.")

    return {
        "tasa_anual": tasa_anual,
        "cap_inicial": cap_inicial,
        "mensual": mensual,
        "extra": extra,
        "años": años,
        "inflacion_tasa": inflacion_tasa,
        "impuesto_pct": impuesto_pct,
        "incremento_anual": incremento_anual,
        "ingresos_mensuales": ingresos_mensuales
    }

def leer_entradas_comparacion(prefijo):
    tasa_anual = st.session_state[f"{prefijo}_interes_anual"] / 100
    cap_inicial = st.session_state[f"{prefijo}_capital_inicial"]
    mensual = st.session_state[f"{prefijo}_aporte_mensual"]
    extra = st.session_state[f"{prefijo}_aporte_extra_anual"]
    años = int(st.session_state[f"{prefijo}_años_inversion"])
    inflacion_tasa = st.session_state[f"{prefijo}_inflacion_estimada"] / 100
    impuesto_pct = st.session_state[f"{prefijo}_impuestos_rescate"] / 100
    incremento_anual = st.session_state[f"{prefijo}_subida_anual_aportes"] / 100
    ingresos_mensuales = st.session_state[f"{prefijo}_ingresos_mensuales"]

    if años <= 0:
        raise ValueError("Los años deben ser mayores que 0.")
    if cap_inicial < 0 or mensual < 0 or extra < 0 or ingresos_mensuales < 0:
        raise ValueError("No se admiten cantidades negativas.")
    if tasa_anual <= -1 or inflacion_tasa <= -1 or impuesto_pct < 0:
        raise ValueError("Revisa los porcentajes introducidos.")

    return {
        "tasa_anual": tasa_anual,
        "cap_inicial": cap_inicial,
        "mensual": mensual,
        "extra": extra,
        "años": años,
        "inflacion_tasa": inflacion_tasa,
        "impuesto_pct": impuesto_pct,
        "incremento_anual": incremento_anual,
        "ingresos_mensuales": ingresos_mensuales
    }


# =========================================================
# SIMULACIÓN PRINCIPAL
# =========================================================
def simular_detallado(
    cap_inicial, aporte_mensual, aporte_extra_anual, años,
    tasa_anual, inflacion_anual, incremento_anual_aporte,
    impuesto_pct, ingresos_mensuales=0
):
    diferencia_real = resumen["capital_bruto"] - resumen["valor_real_hoy"]
    st.info(
        f"Lectura rápida: aportas {formatear_euros(resumen['total_aportado'])}, "
        f"terminas con {formatear_euros(resumen['neto_final'])} netos, "
        f"y la inflación reduce el poder adquisitivo final en aproximadamente "
        f"{formatear_euros(diferencia_real)} frente al valor nominal."
    )
    tasa_mensual = (1 + tasa_anual) ** (1 / 12) - 1
    inflacion_mensual = (1 + inflacion_anual) ** (1 / 12) - 1

    capital = cap_inicial
    aportado_total = cap_inicial
    meses_invirtiendo = 0
    indice_inflacion = 1.0

    mensual_actual = aporte_mensual
    extra_actual = aporte_extra_anual

    historial_nominal = [cap_inicial]
    historial_real = [cap_inicial]

    datos_mensuales = []
    datos_anuales = []

    for año in range(1, años + 1):
        aporte_anual_acumulado = 0.0
        interes_anual_acumulado = 0.0
        capital_inicio_año = capital
        capital_antes_extra_anual = None

        for mes in range(1, 13):
            capital_inicio_mes = capital

            aporte_mes = mensual_actual
            capital += aporte_mes
            aportado_total += aporte_mes
            aporte_anual_acumulado += aporte_mes

            interes_mes = capital * tasa_mensual
            capital += interes_mes
            interes_anual_acumulado += interes_mes

            aporte_extra_mes = 0.0
            if mes == 12:
                capital_antes_extra_anual = capital
                aporte_extra_mes = extra_actual
                capital += aporte_extra_mes
                aportado_total += aporte_extra_mes
                aporte_anual_acumulado += aporte_extra_mes

            indice_inflacion *= (1 + inflacion_mensual)

            meses_invirtiendo += 1
            años_invirtiendo_exactos = meses_invirtiendo / 12

            resultado_acumulado_bruto = capital - aportado_total
            impuestos_estimados = max(resultado_acumulado_bruto, 0) * impuesto_pct
            neto_estimado = capital - impuestos_estimados
            capital_real_mes = capital / indice_inflacion
            neto_real_estimado = neto_estimado / indice_inflacion
            perdida_inflacion = capital - capital_real_mes
            ratio_esfuerzo = (resultado_acumulado_bruto / capital * 100) if capital != 0 else 0
            retirada_segura = (neto_estimado * 0.04) / 12
            tasa_ahorro_anualizada = None

            if ingresos_mensuales > 0:
                tasa_ahorro_anualizada = ((mensual_actual * 12 + extra_actual) / (ingresos_mensuales * 12)) * 100

            datos_mensuales.append({
                "Año": año,
                "Mes": mes,
                "Meses invirtiendo": meses_invirtiendo,
                "Años invirtiendo": round(años_invirtiendo_exactos, 4),
                "Capital inicial del mes": capital_inicio_mes,
                "Aporte mensual": aporte_mes,
                "Aporte extra en este mes": aporte_extra_mes,
                "Aportado acumulado": aportado_total,
                "Interés generado este mes": interes_mes,
                "Resultado acumulado bruto": resultado_acumulado_bruto,
                "Capital total nominal": capital,
                "Índice inflación acumulada": indice_inflacion,
                "Capital total real (euros de hoy)": capital_real_mes,
                "Pérdida por inflación": perdida_inflacion,
                "Rendimiento vs Aportes (%)": ratio_esfuerzo,
                "Impuestos estimados si rescataras aquí": impuestos_estimados,
                "Capital neto estimado": neto_estimado,
                "Capital neto real estimado": neto_real_estimado,
                "Retirada mensual segura (Regla 4%)": retirada_segura,
                "Aporte mensual vigente": mensual_actual,
                "Aporte extra anual vigente": extra_actual,
                "Tasa de ahorro anualizada (%)": tasa_ahorro_anualizada if tasa_ahorro_anualizada is not None else ""
            })

        beneficio_bruto_fin_año = capital - aportado_total
        impuestos_estimados_fin_año = max(beneficio_bruto_fin_año, 0) * impuesto_pct
        neto_estimado_fin_año = capital - impuestos_estimados_fin_año
        capital_real_fin_año = capital / indice_inflacion
        neto_real_fin_año = neto_estimado_fin_año / indice_inflacion
        perdida_inflacion_fin_año = capital - capital_real_fin_año
        ratio_esfuerzo_fin_año = (beneficio_bruto_fin_año / capital * 100) if capital != 0 else 0
        tasa_ahorro_anual_fin = None

        if ingresos_mensuales > 0:
            tasa_ahorro_anual_fin = (aporte_anual_acumulado / (ingresos_mensuales * 12)) * 100

        datos_anuales.append({
            "Año": año,
            "Meses invirtiendo": año * 12,
            "Capital inicio de año": capital_inicio_año,
            "Aporte mensual vigente": mensual_actual,
            "Aporte extra anual vigente": extra_actual,
            "Aportado en el año": aporte_anual_acumulado,
            "Aportado acumulado": aportado_total,
            "Interés generado en el año": interes_anual_acumulado,
            "Capital antes del extra anual": capital_antes_extra_anual if capital_antes_extra_anual is not None else capital,
            "Capital total nominal fin de año": capital,
            "Capital total real fin de año": capital_real_fin_año,
            "Pérdida por inflación": perdida_inflacion_fin_año,
            "Beneficio bruto acumulado": beneficio_bruto_fin_año,
            "Rendimiento vs Aportes (%)": ratio_esfuerzo_fin_año,
            "Impuestos estimados si rescataras ese año": impuestos_estimados_fin_año,
            "Capital neto estimado fin de año": neto_estimado_fin_año,
            "Capital neto real fin de año": neto_real_fin_año,
            "Pensión mensual estimada (regla 4%)": neto_estimado_fin_año * 0.04 / 12,
            "Pensión mensual real estimada": neto_real_fin_año * 0.04 / 12,
            "Índice inflación acumulada": indice_inflacion,
            "Tasa de ahorro anualizada (%)": tasa_ahorro_anual_fin if tasa_ahorro_anual_fin is not None else ""
        })

        historial_nominal.append(capital)
        historial_real.append(capital_real_fin_año)

        mensual_actual *= (1 + incremento_anual_aporte)
        extra_actual *= (1 + incremento_anual_aporte)

    capital_bruto = capital
    beneficio_bruto = capital_bruto - aportado_total
    impuestos = max(beneficio_bruto, 0) * impuesto_pct
    capital_neto = capital_bruto - impuestos
    valor_real_hoy = capital_neto / indice_inflacion
    pension_mensual = capital_neto * 0.04 / 12
    pension_real = valor_real_hoy * 0.04 / 12
    tasa_ahorro = obtener_tasa_ahorro_actual(aporte_mensual, aporte_extra_anual, ingresos_mensuales)
    score_ahorro_val = score_tasa_ahorro(tasa_ahorro)

    resumen = {
        "total_aportado": aportado_total,
        "capital_bruto": capital_bruto,
        "beneficio_bruto": beneficio_bruto,
        "impuestos": impuestos,
        "neto_final": capital_neto,
        "valor_real_hoy": valor_real_hoy,
        "pension_vitalicia": pension_mensual,
        "pension_real": pension_real,
        "tasa_ahorro": tasa_ahorro,
        "score_ahorro": score_ahorro_val,
        "historial_nominal": historial_nominal,
        "historial_real": historial_real
    }

    return datos_mensuales, datos_anuales, resumen




# =========================================================
# EXCEL
# =========================================================
def exportar_excel_bytes(datos_mensuales, datos_anuales, resumen, parametros):
    wb = Workbook()

    ws0 = wb.active
    ws0.title = "Resumen"
    ws0.append(["Concepto", "Valor"])

    resumen_rows = [
        ("Capital inicial", parametros["cap_inicial"]),
        ("Aporte mensual", parametros["mensual"]),
        ("Aporte extra anual", parametros["extra"]),
        ("Años de inversión", parametros["años"]),
        ("Interés anual esperado (%)", parametros["tasa_anual"] * 100),
        ("Inflación estimada (%)", parametros["inflacion_tasa"] * 100),
        ("Impuestos al rescate (%)", parametros["impuesto_pct"] * 100),
        ("Subida anual aportes (%)", parametros["incremento_anual"] * 100),
        ("Ingresos mensuales", parametros["ingresos_mensuales"]),
        ("Total aportado", resumen["total_aportado"]),
        ("Capital bruto", resumen["capital_bruto"]),
        ("Beneficio bruto", resumen["beneficio_bruto"]),
        ("Impuestos", resumen["impuestos"]),
        ("Neto final", resumen["neto_final"]),
        ("Valor real (hoy)", resumen["valor_real_hoy"]),
        ("Pensión estimada", resumen["pension_vitalicia"]),
        ("Pensión real (hoy)", resumen["pension_real"]),
        ("Tasa de ahorro (%)", resumen["tasa_ahorro"] if resumen["tasa_ahorro"] is not None else ""),
        ("Score ahorro", resumen["score_ahorro"]),
    ]
    for row in resumen_rows:
        ws0.append(row)

    ws1 = wb.create_sheet("Mes a mes")
    if datos_mensuales:
        headers_1 = list(datos_mensuales[0].keys())
        ws1.append(headers_1)
        for fila in datos_mensuales:
            ws1.append(list(fila.values()))

    ws2 = wb.create_sheet("Año a año")
    if datos_anuales:
        headers_2 = list(datos_anuales[0].keys())
        ws2.append(headers_2)
        for fila in datos_anuales:
            ws2.append(list(fila.values()))

    ws3 = wb.create_sheet("Guía columnas")
    ws3.append(["Columna", "Explicación"])
    for col, desc in GUIA_COLUMNAS_EXCEL.items():
        ws3.append([col, desc])

    for ws in [ws0, ws1, ws2, ws3]:
        aplicar_formato_excel(ws)

    output = BytesIO()
    wb.save(output)
    output.seek(0)
    return output.getvalue()


# =========================================================
# GRÁFICAS
# =========================================================
def crear_figura_principal(años, hist_esp, hist_opt, hist_pes, hist_real_esp, aportado, tax, bruto):
    fig = plt.figure(figsize=(15, 5))
    eje_x = range(años + 1)

    ax1 = fig.add_subplot(1, 3, 1)
    ax1.plot(eje_x, hist_opt, '--', label='Optimista (+2%)', alpha=0.7)
    ax1.plot(eje_x, hist_esp, linewidth=3, label='Plan esperado')
    ax1.plot(eje_x, hist_pes, '--', label='Pesimista (-2%)', alpha=0.7)
    ax1.fill_between(eje_x, hist_pes, hist_opt, alpha=0.15)
    ax1.set_title("Evolución nominal")
    ax1.set_xlabel("Años")
    ax1.set_ylabel("Euros (€)")
    ax1.legend()
    ax1.grid(True, linestyle='--', alpha=0.5)

    ax2 = fig.add_subplot(1, 3, 2)
    ax2.plot(eje_x, hist_real_esp, linewidth=3, label='Capital real')
    ax2.set_title("Evolución real (euros de hoy)")
    ax2.set_xlabel("Años")
    ax2.set_ylabel("Euros reales")
    ax2.legend()
    ax2.grid(True, linestyle='--', alpha=0.5)

    ax3 = fig.add_subplot(1, 3, 3)
    ganancia_neta = bruto - aportado - tax
    if ganancia_neta < 0:
        ganancia_neta = 0

    sizes = [max(aportado, 0), max(ganancia_neta, 0), max(tax, 0)]
    labels = ['Tus aportes', 'Intereses netos', 'Impuestos']
    explode = (0, 0.05, 0.1)
    ax3.pie(sizes, labels=labels, autopct='%1.1f%%', startangle=140, explode=explode)
    ax3.set_title("Composición del capital final")

    plt.tight_layout()
    return fig

def crear_figura_regla_4():
    capitales = [50000, 100000, 200000, 300000, 500000, 750000, 1000000]
    pensiones = [(c * 0.04) / 12 for c in capitales]

    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(capitales, pensiones, marker='o')
    ax.set_title("Regla del 4%: capital vs retirada mensual")
    ax.set_xlabel("Capital acumulado (€)")
    ax.set_ylabel("Retirada mensual estimada (€)")
    ax.grid(True, linestyle="--", alpha=0.5)

    for x, y in zip(capitales, pensiones):
        ax.annotate(f"{y:,.0f}€/mes", (x, y), textcoords="offset points", xytext=(0, 8), ha='center')

    plt.tight_layout()
    return fig

def crear_figura_comparacion(nombre_a, nombre_b, resumen_a, resumen_b, años):
    fig = plt.figure(figsize=(14, 5))
    eje_x = range(años + 1)

    ax1 = fig.add_subplot(1, 2, 1)
    ax1.plot(eje_x, resumen_a["historial_nominal"], linewidth=3, label=nombre_a)
    ax1.plot(eje_x, resumen_b["historial_nominal"], linewidth=3, label=nombre_b)
    ax1.set_title("Comparación nominal")
    ax1.set_xlabel("Años")
    ax1.set_ylabel("Euros (€)")
    ax1.legend()
    ax1.grid(True, linestyle="--", alpha=0.5)

    ax2 = fig.add_subplot(1, 2, 2)
    ax2.plot(eje_x, resumen_a["historial_real"], linewidth=3, label=f"{nombre_a} (real)")
    ax2.plot(eje_x, resumen_b["historial_real"], linewidth=3, label=f"{nombre_b} (real)")
    ax2.set_title("Comparación real (euros de hoy)")
    ax2.set_xlabel("Años")
    ax2.set_ylabel("Euros reales")
    ax2.legend()
    ax2.grid(True, linestyle="--", alpha=0.5)

    plt.tight_layout()
    return fig


# =========================================================
# CÁLCULOS ADICIONALES
# =========================================================
def calcular_inflacion_educativa(monto, infla_pct, años):
    infla = infla_pct / 100
    valor_futuro_equivalente = monto * ((1 + infla) ** años)
    valor_real_futuro = monto / ((1 + infla) ** años)

    return (
        f"Para conservar el poder adquisitivo de {formatear_euros(monto)} hoy,\n"
        f"necesitarías {formatear_euros(valor_futuro_equivalente)} dentro de {años} años.\n\n"
        f"Y si dentro de {años} años tuvieras {formatear_euros(monto)},\n"
        f"su valor real sería de solo {formatear_euros(valor_real_futuro)} en euros de hoy."
    )

def simular_optimizacion_fiscal(capital_inicial, aporte_anual, años, rentabilidad_pct, impuesto_pct, rotacion_pct):
    rentabilidad = rentabilidad_pct / 100
    impuesto = impuesto_pct / 100
    rotacion = rotacion_pct / 100

    if años <= 0:
        raise ValueError("Los años deben ser mayores que 0.")
    if any(x < 0 for x in [capital_inicial, aporte_anual, impuesto, rotacion]):
        raise ValueError("No se admiten valores negativos.")

    capital_fondo = capital_inicial
    capital_etf = capital_inicial
    aportado_fondo = capital_inicial
    aportado_etf = capital_inicial
    impuestos_pagados_durante = 0.0

    for _ in range(años):
        capital_fondo += aporte_anual
        capital_etf += aporte_anual
        aportado_fondo += aporte_anual
        aportado_etf += aporte_anual

        capital_fondo *= (1 + rentabilidad)
        capital_etf *= (1 + rentabilidad)

        beneficio_latente_etf = capital_etf - aportado_etf
        if capital_etf > 0 and beneficio_latente_etf > 0 and rotacion > 0:
            porcentaje_plusvalia_en_la_cartera = beneficio_latente_etf / capital_etf
            venta_anual = capital_etf * rotacion
            ganancia_realizada = venta_anual * porcentaje_plusvalia_en_la_cartera
            impuesto_anual = ganancia_realizada * impuesto
            capital_etf -= impuesto_anual
            impuestos_pagados_durante += impuesto_anual

    impuesto_final_fondo = max(capital_fondo - aportado_fondo, 0) * impuesto
    neto_fondo = capital_fondo - impuesto_final_fondo

    impuesto_final_etf = max(capital_etf - aportado_etf, 0) * impuesto
    neto_etf = capital_etf - impuesto_final_etf

    ventaja_fondo = neto_fondo - neto_etf

    return (
        f"Resultado simplificado educativo:\n\n"
        f"Fondo traspasable:\n"
        f"- Capital bruto final: {formatear_euros(capital_fondo)}\n"
        f"- Impuesto final estimado: {formatear_euros(impuesto_final_fondo)}\n"
        f"- Neto final: {formatear_euros(neto_fondo)}\n\n"
        f"ETF / Acciones con ventas periódicas:\n"
        f"- Capital bruto final: {formatear_euros(capital_etf)}\n"
        f"- Impuestos pagados durante el camino: {formatear_euros(impuestos_pagados_durante)}\n"
        f"- Impuesto final estimado: {formatear_euros(impuesto_final_etf)}\n"
        f"- Neto final: {formatear_euros(neto_etf)}\n\n"
        f"Ventaja estimada del vehículo fiscalmente eficiente: {formatear_euros(ventaja_fondo)}"
    )

def proyectar_libertad_financiera(objetivo_mensual, max_años_busqueda):
    params = leer_entradas_principales()

    tasa_mensual = (1 + params["tasa_anual"]) ** (1 / 12) - 1
    inflacion_mensual = (1 + params["inflacion_tasa"]) ** (1 / 12) - 1

    capital = params["cap_inicial"]
    aportado_total = params["cap_inicial"]
    mensual_actual = params["mensual"]
    extra_actual = params["extra"]
    indice_inflacion = 1.0

    meses = 0
    mejor_pension_real = 0.0
    mejor_neto_real = 0.0
    mejor_mes = 0

    for _año in range(1, max_años_busqueda + 1):
        for mes in range(1, 13):
            capital += mensual_actual
            aportado_total += mensual_actual
            capital *= (1 + tasa_mensual)

            if mes == 12:
                capital += extra_actual
                aportado_total += extra_actual

            indice_inflacion *= (1 + inflacion_mensual)
            meses += 1

            beneficio = capital - aportado_total
            impuestos = max(beneficio, 0) * params["impuesto_pct"]
            neto = capital - impuestos
            neto_real = neto / indice_inflacion
            pension_real = neto_real * 0.04 / 12

            if pension_real > mejor_pension_real:
                mejor_pension_real = pension_real
                mejor_neto_real = neto_real
                mejor_mes = meses

            if pension_real >= objetivo_mensual:
                return {
                    "alcanzado": True,
                    "meses": meses,
                    "años": meses / 12,
                    "capital_neto_real": neto_real,
                    "pension_real": pension_real,
                    "aportado_total": aportado_total
                }

        mensual_actual *= (1 + params["incremento_anual"])
        extra_actual *= (1 + params["incremento_anual"])

    return {
        "alcanzado": False,
        "mejor_pension_real": mejor_pension_real,
        "mejor_capital_neto_real": mejor_neto_real,
        "mejor_mes": mejor_mes,
        "mejor_años": mejor_mes / 12 if mejor_mes else max_años_busqueda,
        "aportado_total": aportado_total
    }


def calcular_libertad_financiera():
    params = leer_entradas_principales()
    objetivo_mensual = st.session_state["libertad_objetivo"]
    max_años = int(st.session_state["libertad_max_años"])

    if objetivo_mensual <= 0:
        raise ValueError("El objetivo mensual debe ser mayor que 0.")
    if max_años <= 0:
        raise ValueError("El máximo de años debe ser mayor que 0.")

    capital_objetivo_hoy = objetivo_mensual * 12 / 0.04

    resultado_limite = proyectar_libertad_financiera(objetivo_mensual, max_años)

    if resultado_limite["alcanzado"]:
        return (
            f"Objetivo alcanzado dentro del plazo indicado.\n\n"
            f"Para generar aproximadamente {formatear_euros(objetivo_mensual)}/mes en euros de hoy "
            f"con la regla del 4%, necesitarías aproximadamente un capital neto real de "
            f"{formatear_euros(capital_objetivo_hoy)}.\n\n"
            f"Con tus parámetros actuales lo alcanzarías en:\n"
            f"- {resultado_limite['meses']} meses\n"
            f"- {resultado_limite['años']:.2f} años\n\n"
            f"Capital neto real aproximado en ese momento: {formatear_euros(resultado_limite['capital_neto_real'])}\n"
            f"Pensión real estimada: {formatear_euros(resultado_limite['pension_real'])}/mes"
        )

    resultado_extendido = proyectar_libertad_financiera(objetivo_mensual, 120)

    if resultado_extendido["alcanzado"]:
        return (
            f"No se alcanza el objetivo dentro del límite de {max_años} años.\n\n"
            f"Para obtener {formatear_euros(objetivo_mensual)}/mes en euros de hoy, "
            f"necesitarías aproximadamente {formatear_euros(capital_objetivo_hoy)} "
            f"de capital neto real aplicando la regla del 4%.\n\n"
            f"Con los parámetros actuales sí sería posible, pero el plazo mínimo estimado sería de:\n"
            f"- {resultado_extendido['meses']} meses\n"
            f"- {resultado_extendido['años']:.2f} años\n\n"
            f"Lo máximo que consigues dentro de tu límite actual de {max_años} años es una pensión real aproximada de "
            f"{formatear_euros(resultado_limite['mejor_pension_real'])}/mes."
        )

    return (
        f"No se alcanza el objetivo de {formatear_euros(objetivo_mensual)}/mes ni siquiera ampliando mucho el horizonte.\n\n"
        f"Capital neto real orientativo que haría falta para ese objetivo: {formatear_euros(capital_objetivo_hoy)}.\n\n"
        f"Con los parámetros actuales, lo máximo estimado que llegarías a generar sería "
        f"{formatear_euros(resultado_limite['mejor_pension_real'])}/mes dentro de {max_años} años.\n"
        f"Capital neto real aproximado en ese punto: {formatear_euros(resultado_limite['mejor_capital_neto_real'])}.\n\n"
        f"Para acercarte al objetivo, prueba a aumentar aportes, ampliar plazo o revisar la rentabilidad esperada."
    )


# =========================================================
# ACCIONES PRINCIPALES
# =========================================================
def calcular_simulacion():
    params = leer_entradas_principales()

    datos_mensuales, datos_anuales, resumen = simular_detallado(
        cap_inicial=params["cap_inicial"],
        aporte_mensual=params["mensual"],
        aporte_extra_anual=params["extra"],
        años=params["años"],
        tasa_anual=params["tasa_anual"],
        inflacion_anual=params["inflacion_tasa"],
        incremento_anual_aporte=params["incremento_anual"],
        impuesto_pct=params["impuesto_pct"],
        ingresos_mensuales=params["ingresos_mensuales"]
    )

    _, _, resumen_opt = simular_detallado(
        cap_inicial=params["cap_inicial"],
        aporte_mensual=params["mensual"],
        aporte_extra_anual=params["extra"],
        años=params["años"],
        tasa_anual=params["tasa_anual"] + 0.02,
        inflacion_anual=params["inflacion_tasa"],
        incremento_anual_aporte=params["incremento_anual"],
        impuesto_pct=params["impuesto_pct"],
        ingresos_mensuales=params["ingresos_mensuales"]
    )

    tasa_pes = max(params["tasa_anual"] - 0.02, -0.99)
    _, _, resumen_pes = simular_detallado(
        cap_inicial=params["cap_inicial"],
        aporte_mensual=params["mensual"],
        aporte_extra_anual=params["extra"],
        años=params["años"],
        tasa_anual=tasa_pes,
        inflacion_anual=params["inflacion_tasa"],
        incremento_anual_aporte=params["incremento_anual"],
        impuesto_pct=params["impuesto_pct"],
        ingresos_mensuales=params["ingresos_mensuales"]
    )

    st.session_state["ultima_simulacion"] = {
        "params": params,
        "datos_mensuales": datos_mensuales,
        "datos_anuales": datos_anuales,
        "resumen": resumen,
        "resumen_opt": resumen_opt,
        "resumen_pes": resumen_pes
    }
    st.session_state["estado_simulacion"] = (
        "Simulación calculada correctamente. Ya puedes ver gráficos, tablas y descargar el Excel."
    )


# =========================================================
# UI
# =========================================================
st.title("📊 PLANIFICADOR FINANCIERO")
st.write("Calculadora de pensión, simulación de libertad financiera, educación financiera y exportación a Excel.")

tabs = st.tabs([
    "📊 Simulación",
    "🎓 Academia",
    "🧾 Optimización Fiscal",
    "🗽 Libertad Financiera",
    "📚 Comparativa de Activos",
    "📄 Guía del Excel"
])


# =========================================================
# TAB 1 - SIMULACIÓN
# =========================================================
with tabs[0]:
    sim_subtabs = st.tabs(["📌 Plan de jubilación", "⚖️ Comparar 2 planes"])

    with sim_subtabs[0]:
        st.subheader("Datos de entrada")

        if st.session_state.get("mensaje_rentabilidad_copiada"):
            st.success(st.session_state["mensaje_rentabilidad_copiada"])

    with st.expander("Ayuda de los campos de entrada"):
        for clave in ["int", "cap", "mensual", "inc", "extra", "años", "infla", "tax", "ingresos"]:
            st.markdown(f"**{AYUDAS_ENTRADAS[clave]['titulo']}**")
            st.write(AYUDAS_ENTRADAS[clave]["texto"])

    c1, c2, c3 = st.columns(3)

    with c1:
        st.number_input(
            "Interés anual esperado (%)",
            min_value=-99.0,
            max_value=1000.0,
            step=0.1,
            key="interes_anual"
        )
        st.number_input(
            "Capital inicial (€)",
            min_value=0.0,
            step=100.0,
            key="capital_inicial"
        )
        st.number_input(
            "Aporte mensual (€)",
            min_value=0.0,
            step=10.0,
            key="aporte_mensual"
        )

    with c2:
        st.number_input(
            "Subida anual aportes (%)",
            min_value=0.0,
            max_value=1000.0,
            step=0.1,
            key="subida_anual_aportes"
        )
        st.number_input(
            "Aporte extra anual (€)",
            min_value=0.0,
            step=10.0,
            key="aporte_extra_anual"
        )
        st.number_input(
            "Años de inversión",
            min_value=1,
            max_value=100,
            step=1,
            key="años_inversion"
        )

    with c3:
        st.number_input(
            "Inflación estimada (%)",
            min_value=-99.0,
            max_value=1000.0,
            step=0.1,
            key="inflacion_estimada"
        )
        st.number_input(
            "Impuestos al rescate (%)",
            min_value=0.0,
            max_value=100.0,
            step=0.1,
            key="impuestos_rescate"
        )
        st.number_input(
            "Ingresos mensuales (€)",
            min_value=0.0,
            step=50.0,
            key="ingresos_mensuales"
        )

    st.markdown("### Acciones")
    a1, a2, a3 = st.columns(3)

    with a1:
        if st.button("CALCULAR", use_container_width=True):
            try:
                calcular_simulacion()
                st.success("La simulación se ha calculado correctamente.")
            except Exception as e:
                st.error(f"Revisa los datos introducidos. Detalle: {e}")

    with a2:
        if st.session_state["ultima_simulacion"] is not None:
            sim = st.session_state["ultima_simulacion"]
            excel_bytes = exportar_excel_bytes(
                sim["datos_mensuales"],
                sim["datos_anuales"],
                sim["resumen"],
                sim["params"]
            )
            st.download_button(
                "GENERAR EXCEL",
                data=excel_bytes,
                file_name=f"simulacion_jubilacion_{datetime.now().strftime('%Y%m%d_%H%M%S')}.xlsx",
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                use_container_width=True
            )
        else:
            st.button("GENERAR EXCEL", disabled=True, use_container_width=True)

    with a3:
        if st.session_state["ultima_simulacion"] is None:
            st.button("VER GRÁFICOS", disabled=True, use_container_width=True)
        else:
            if st.button("VER GRÁFICOS", use_container_width=True):
                pass

    st.info(st.session_state["estado_simulacion"])

    st.markdown("### Perfil JSON")
    p1, p2 = st.columns(2)

    with p1:
        perfil = {
            "interes_anual": st.session_state["interes_anual"],
            "capital_inicial": st.session_state["capital_inicial"],
            "aporte_mensual": st.session_state["aporte_mensual"],
            "subida_anual_aportes": st.session_state["subida_anual_aportes"],
            "aporte_extra_anual": st.session_state["aporte_extra_anual"],
            "años_inversion": st.session_state["años_inversion"],
            "inflacion_estimada": st.session_state["inflacion_estimada"],
            "impuestos_rescate": st.session_state["impuestos_rescate"],
            "ingresos_mensuales": st.session_state["ingresos_mensuales"]
        }
        st.download_button(
            "GUARDAR PERFIL JSON",
            data=json.dumps(perfil, ensure_ascii=False, indent=4),
            file_name="perfil_financiero.json",
            mime="application/json",
            use_container_width=True
        )

    with p2:
        archivo_perfil = st.file_uploader("CARGAR PERFIL JSON", type=["json"], key="perfil_json")
        if archivo_perfil is not None:
            try:
                datos = json.load(archivo_perfil)
                mapping = {
                    "interes_anual": "interes_anual",
                    "capital_inicial": "capital_inicial",
                    "aporte_mensual": "aporte_mensual",
                    "subida_anual_aportes": "subida_anual_aportes",
                    "aporte_extra_anual": "aporte_extra_anual",
                    "años_inversion": "años_inversion",
                    "inflacion_estimada": "inflacion_estimada",
                    "impuestos_rescate": "impuestos_rescate",
                    "ingresos_mensuales": "ingresos_mensuales"
                }
                for origen, destino in mapping.items():
                    if origen in datos:
                        st.session_state[destino] = datos[origen]
                st.success("Perfil cargado correctamente.")
            except Exception as e:
                st.error(f"No se pudo cargar el perfil. Detalle: {e}")

    if st.session_state["ultima_simulacion"] is not None:
        sim = st.session_state["ultima_simulacion"]
        resumen = sim["resumen"]
        resumen_opt = sim["resumen_opt"]
        resumen_pes = sim["resumen_pes"]
        params = sim["params"]

        st.markdown("## Resultados")

        m1, m2, m3 = st.columns(3)
        m4, m5, m6 = st.columns(3)
        m7, m8, m9, m10 = st.columns(4)

        m1.metric("💰 Total aportado", formatear_euros(resumen["total_aportado"]))
        m2.metric("📈 Capital bruto", formatear_euros(resumen["capital_bruto"]))
        m3.metric("🧠 Beneficio bruto", formatear_euros(resumen["beneficio_bruto"]))

        m4.metric("💸 Impuestos", f"-{formatear_euros(resumen['impuestos'])}")
        m5.metric("✅ Neto final", formatear_euros(resumen["neto_final"]))
        m6.metric("📉 Valor real (hoy)", formatear_euros(resumen["valor_real_hoy"]))

        m7.metric("🏦 Pensión estimada", f"{formatear_euros(resumen['pension_vitalicia'])}/mes")
        m8.metric("🛒 Pensión real (hoy)", f"{formatear_euros(resumen['pension_real'])}/mes")
        m9.metric(
            "📊 Tasa de ahorro",
            formatear_pct(resumen["tasa_ahorro"]) if resumen["tasa_ahorro"] is not None else "No calculable"
        )
        m10.metric("⭐ Score de ahorro", resumen["score_ahorro"])

        with st.expander("Ayuda de los resultados"):
            for clave, texto in AYUDAS_SALIDA.items():
                st.markdown(f"**{clave}**")
                st.write(texto)

        st.markdown("## Gráficos")
        fig = crear_figura_principal(
            años=params["años"],
            hist_esp=resumen["historial_nominal"],
            hist_opt=resumen_opt["historial_nominal"],
            hist_pes=resumen_pes["historial_nominal"],
            hist_real_esp=resumen["historial_real"],
            aportado=resumen["total_aportado"],
            tax=resumen["impuestos"],
            bruto=resumen["capital_bruto"]
        )
        st.pyplot(fig)

        st.markdown("## Tablas")
        sub1, sub2 = st.tabs(["Mes a mes", "Año a año"])

        with sub1:
            df_mensual = pd.DataFrame(sim["datos_mensuales"])
            st.dataframe(df_mensual, use_container_width=True)

        with sub2:
            df_anual = pd.DataFrame(sim["datos_anuales"])
            st.dataframe(df_anual, use_container_width=True)


    with sim_subtabs[1]:
        st.subheader("Comparador de 2 planes de jubilación")
        st.write(
            "Aquí puedes enfrentar dos estrategias distintas y ver cuál llega más lejos. "
            "Sirve para comparar, por ejemplo, más aportación vs más rentabilidad, "
            "más plazo vs más ahorro, o planes prudentes frente a agresivos."
        )

        st.info(
            "Este comparador muestra métricas y gráficos, pero no genera Excel. "
            "La exportación sigue disponible solo en el plan principal."
        )

        col_a, col_b = st.columns(2)

        with col_a:
            st.markdown("### Plan A")
            st.text_input("Nombre del plan A", key="comp_a_nombre")
            st.number_input("Interés anual esperado A (%)", min_value=-99.0, max_value=1000.0, step=0.1, key="comp_a_interes_anual")
            st.number_input("Capital inicial A (€)", min_value=0.0, step=100.0, key="comp_a_capital_inicial")
            st.number_input("Aporte mensual A (€)", min_value=0.0, step=10.0, key="comp_a_aporte_mensual")
            st.number_input("Subida anual aportes A (%)", min_value=0.0, max_value=1000.0, step=0.1, key="comp_a_subida_anual_aportes")
            st.number_input("Aporte extra anual A (€)", min_value=0.0, step=10.0, key="comp_a_aporte_extra_anual")
            st.number_input("Años de inversión A", min_value=1, max_value=100, step=1, key="comp_a_años_inversion")
            st.number_input("Inflación estimada A (%)", min_value=-99.0, max_value=1000.0, step=0.1, key="comp_a_inflacion_estimada")
            st.number_input("Impuestos al rescate A (%)", min_value=0.0, max_value=100.0, step=0.1, key="comp_a_impuestos_rescate")
            st.number_input("Ingresos mensuales A (€)", min_value=0.0, step=50.0, key="comp_a_ingresos_mensuales")

        with col_b:
            st.markdown("### Plan B")
            st.text_input("Nombre del plan B", key="comp_b_nombre")
            st.number_input("Interés anual esperado B (%)", min_value=-99.0, max_value=1000.0, step=0.1, key="comp_b_interes_anual")
            st.number_input("Capital inicial B (€)", min_value=0.0, step=100.0, key="comp_b_capital_inicial")
            st.number_input("Aporte mensual B (€)", min_value=0.0, step=10.0, key="comp_b_aporte_mensual")
            st.number_input("Subida anual aportes B (%)", min_value=0.0, max_value=1000.0, step=0.1, key="comp_b_subida_anual_aportes")
            st.number_input("Aporte extra anual B (€)", min_value=0.0, step=10.0, key="comp_b_aporte_extra_anual")
            st.number_input("Años de inversión B", min_value=1, max_value=100, step=1, key="comp_b_años_inversion")
            st.number_input("Inflación estimada B (%)", min_value=-99.0, max_value=1000.0, step=0.1, key="comp_b_inflacion_estimada")
            st.number_input("Impuestos al rescate B (%)", min_value=0.0, max_value=100.0, step=0.1, key="comp_b_impuestos_rescate")
            st.number_input("Ingresos mensuales B (€)", min_value=0.0, step=50.0, key="comp_b_ingresos_mensuales")

        if st.button("Comparar planes", use_container_width=True):
            try:
                params_a = leer_entradas_comparacion("comp_a")
                params_b = leer_entradas_comparacion("comp_b")

                _, datos_anuales_a, resumen_a = simular_detallado(
                    cap_inicial=params_a["cap_inicial"],
                    aporte_mensual=params_a["mensual"],
                    aporte_extra_anual=params_a["extra"],
                    años=params_a["años"],
                    tasa_anual=params_a["tasa_anual"],
                    inflacion_anual=params_a["inflacion_tasa"],
                    incremento_anual_aporte=params_a["incremento_anual"],
                    impuesto_pct=params_a["impuesto_pct"],
                    ingresos_mensuales=params_a["ingresos_mensuales"]
                )

                _, datos_anuales_b, resumen_b = simular_detallado(
                    cap_inicial=params_b["cap_inicial"],
                    aporte_mensual=params_b["mensual"],
                    aporte_extra_anual=params_b["extra"],
                    años=params_b["años"],
                    tasa_anual=params_b["tasa_anual"],
                    inflacion_anual=params_b["inflacion_tasa"],
                    incremento_anual_aporte=params_b["incremento_anual"],
                    impuesto_pct=params_b["impuesto_pct"],
                    ingresos_mensuales=params_b["ingresos_mensuales"]
                )

                nombre_a = st.session_state["comp_a_nombre"].strip() or "Plan A"
                nombre_b = st.session_state["comp_b_nombre"].strip() or "Plan B"

                st.markdown("## Resultado comparado")

                c1, c2, c3, c4 = st.columns(4)
                c1.metric(
                    f"Neto final · {nombre_a}",
                    formatear_euros(resumen_a["neto_final"])
                )
                c2.metric(
                    f"Neto final · {nombre_b}",
                    formatear_euros(resumen_b["neto_final"]),
                    delta=formatear_euros(resumen_b["neto_final"] - resumen_a["neto_final"])
                )
                c3.metric(
                    f"Pensión real · {nombre_a}",
                    f"{formatear_euros(resumen_a['pension_real'])}/mes"
                )
                c4.metric(
                    f"Pensión real · {nombre_b}",
                    f"{formatear_euros(resumen_b['pension_real'])}/mes",
                    delta=formatear_euros(resumen_b["pension_real"] - resumen_a["pension_real"])
                )

                mejor_neto = nombre_a if resumen_a["neto_final"] >= resumen_b["neto_final"] else nombre_b
                mejor_pension = nombre_a if resumen_a["pension_real"] >= resumen_b["pension_real"] else nombre_b

                st.info(
                    f"El plan con mayor capital neto final es **{mejor_neto}**. "
                    f"El plan con mayor pensión real estimada es **{mejor_pension}**."
                )

                años_grafica = min(
                    len(resumen_a["historial_nominal"]) - 1,
                    len(resumen_b["historial_nominal"]) - 1
                )

                resumen_a_graf = {
                    "historial_nominal": resumen_a["historial_nominal"][:años_grafica + 1],
                    "historial_real": resumen_a["historial_real"][:años_grafica + 1]
                }
                resumen_b_graf = {
                    "historial_nominal": resumen_b["historial_nominal"][:años_grafica + 1],
                    "historial_real": resumen_b["historial_real"][:años_grafica + 1]
                }

                fig_comp = crear_figura_comparacion(
                    nombre_a,
                    nombre_b,
                    resumen_a_graf,
                    resumen_b_graf,
                    años_grafica
                )
                st.pyplot(fig_comp)

                tabla_comparativa = pd.DataFrame([
                    {
                        "Métrica": "Total aportado",
                        nombre_a: resumen_a["total_aportado"],
                        nombre_b: resumen_b["total_aportado"],
                    },
                    {
                        "Métrica": "Capital bruto",
                        nombre_a: resumen_a["capital_bruto"],
                        nombre_b: resumen_b["capital_bruto"],
                    },
                    {
                        "Métrica": "Beneficio bruto",
                        nombre_a: resumen_a["beneficio_bruto"],
                        nombre_b: resumen_b["beneficio_bruto"],
                    },
                    {
                        "Métrica": "Impuestos",
                        nombre_a: resumen_a["impuestos"],
                        nombre_b: resumen_b["impuestos"],
                    },
                    {
                        "Métrica": "Neto final",
                        nombre_a: resumen_a["neto_final"],
                        nombre_b: resumen_b["neto_final"],
                    },
                    {
                        "Métrica": "Valor real hoy",
                        nombre_a: resumen_a["valor_real_hoy"],
                        nombre_b: resumen_b["valor_real_hoy"],
                    },
                    {
                        "Métrica": "Pensión estimada",
                        nombre_a: resumen_a["pension_vitalicia"],
                        nombre_b: resumen_b["pension_vitalicia"],
                    },
                    {
                        "Métrica": "Pensión real",
                        nombre_a: resumen_a["pension_real"],
                        nombre_b: resumen_b["pension_real"],
                    },
                ])

                st.markdown("### Tabla comparativa")
                st.dataframe(tabla_comparativa, use_container_width=True)

                st.markdown("### Vista año a año")
                vista_a = pd.DataFrame(datos_anuales_a).copy()
                vista_b = pd.DataFrame(datos_anuales_b).copy()

                vista_a["Plan"] = nombre_a
                vista_b["Plan"] = nombre_b

                columnas_utiles = [
                    "Plan",
                    "Año",
                    "Aportado acumulado",
                    "Capital total nominal fin de año",
                    "Capital neto estimado fin de año",
                    "Capital neto real fin de año",
                    "Pensión mensual real estimada",
                ]

                df_union = pd.concat([vista_a[columnas_utiles], vista_b[columnas_utiles]], ignore_index=True)
                st.dataframe(df_union, use_container_width=True)

            except Exception as e:
                st.error(f"No se pudo comparar los planes. Detalle: {e}")


# =========================================================
# TAB 2 - ACADEMIA
# =========================================================
with tabs[1]:
    st.subheader("ACADEMIA INTERACTIVA")

    st.write(
        "1. **INTERÉS COMPUESTO**\n"
        "Es el efecto bola de nieve. Lo ganado se reinvierte y vuelve a producir ganancias.\n\n"
        "2. **INFLACIÓN Y PODER ADQUISITIVO**\n"
        "No importa solo cuánto dinero tendrás, sino qué podrás comprar con él.\n\n"
        "3. **APORTACIONES CRECIENTES**\n"
        "Ahorrar un poco más cada año puede cambiar muchísimo el resultado final.\n\n"
        "4. **REGLA DEL 4%**\n"
        "Se usa como referencia para estimar una retirada anual relativamente sostenible.\n\n"
        "5. **IMPUESTOS**\n"
        "El capital bruto no es lo mismo que el dinero real que te queda después de Hacienda."
    )

    st.markdown("### Mini calculadora educativa: efecto de la inflación")
    c1, c2, c3 = st.columns(3)

    with c1:
        st.number_input("Monto hoy (€)", min_value=0.0, step=10.0, key="acad_monto")
    with c2:
        st.number_input("Inflación (%)", min_value=-99.0, max_value=1000.0, step=0.1, key="acad_infla")
    with c3:
        st.number_input("Años", min_value=1, max_value=200, step=1, key="acad_años")

    if st.button("Ver efecto de la inflación"):
        try:
            resultado = calcular_inflacion_educativa(
                st.session_state["acad_monto"],
                st.session_state["acad_infla"],
                int(st.session_state["acad_años"])
            )
            st.success("Cálculo realizado.")
            st.write(resultado)
        except Exception as e:
            st.error(f"No se pudo calcular el efecto de la inflación. Detalle: {e}")

    st.markdown("### Visualización educativa de la Regla del 4%")
    st.write(
        "La idea es sencilla: cuanto más capital tengas, mayor 'nómina financiera' "
        "podrías extraer manteniendo una retirada prudente."
    )
    if st.button("Mostrar gráfico educativo de la Regla del 4%"):
        fig = crear_figura_regla_4()
        st.pyplot(fig)


# =========================================================
# TAB 3 - OPTIMIZACIÓN FISCAL
# =========================================================
with tabs[2]:
    st.subheader("OPTIMIZACIÓN FISCAL")
    st.write(
        "Esta pestaña hace una comparación simplificada y educativa entre un vehículo fiscalmente eficiente "
        "tipo fondo traspasable y una cartera donde se generan impuestos por ventas periódicas, "
        "como puede ocurrir con acciones o ETFs si rebalanceas y materializas ganancias.\n\n"
        "No sustituye asesoramiento fiscal profesional, pero sirve para entender el efecto del tax drag."
    )

    f1, f2, f3 = st.columns(3)

    with f1:
        st.number_input("Capital inicial (€)", min_value=0.0, step=100.0, key="fiscal_capital_inicial")
        st.number_input("Aporte anual (€)", min_value=0.0, step=100.0, key="fiscal_aporte_anual")

    with f2:
        st.number_input("Años", min_value=1, max_value=100, step=1, key="fiscal_años")
        st.number_input("Rentabilidad anual (%)", min_value=-99.0, max_value=1000.0, step=0.1, key="fiscal_rentabilidad")

    with f3:
        st.number_input("Impuesto (%)", min_value=0.0, max_value=100.0, step=0.1, key="fiscal_impuesto")
        st.number_input("Rotación anual cartera (%)", min_value=0.0, max_value=100.0, step=0.1, key="fiscal_rotacion")

    if st.button("Calcular comparación fiscal"):
        try:
            texto = simular_optimizacion_fiscal(
                st.session_state["fiscal_capital_inicial"],
                st.session_state["fiscal_aporte_anual"],
                int(st.session_state["fiscal_años"]),
                st.session_state["fiscal_rentabilidad"],
                st.session_state["fiscal_impuesto"],
                st.session_state["fiscal_rotacion"]
            )
            st.success("Comparación calculada.")
            st.write(texto)
        except Exception as e:
            st.error(f"No se pudo hacer el cálculo fiscal. Detalle: {e}")


# =========================================================
# TAB 4 - LIBERTAD FINANCIERA
# =========================================================
with tabs[3]:
    st.subheader("LIBERTAD FINANCIERA")
    st.write(
        "Esta pestaña hace el cálculo inverso al plan de jubilación.\n\n"
        "En vez de preguntarte cuánto capital tendrás dentro de X años, aquí preguntas:\n"
        "**cuánto tiempo tardaría mi cartera en generar una cantidad mensual concreta**.\n\n"
        "La referencia utilizada es la **regla del 4%**, aplicada sobre el capital neto y ajustada a inflación, "
        "por lo que el resultado se expresa en **euros de hoy**."
    )

    with st.expander("Cómo interpretar esta pestaña"):
        st.write(
            "**Dinero deseado al mes (euros de hoy)**:\n"
            "es la cantidad mensual que querrías poder sacar de tu cartera manteniendo poder adquisitivo actual.\n\n"
            "**Máximo de años a simular**:\n"
            "es el horizonte que tú quieres poner como límite para comprobar si llegas o no.\n\n"
            "Ejemplo:\n"
            "- Si pones 1.500 €/mes y 25 años, la app te dirá si con tu plan actual puedes llegar a generar "
            "ese importe mensual real dentro de 25 años.\n"
            "- Si no llegas, ahora también te dirá qué máximo alcanzarías y, si fuera posible más adelante, "
            "el plazo mínimo estimado para conseguirlo."
        )

    capital_objetivo = st.session_state["libertad_objetivo"] * 12 / 0.04
    st.info(
        f"Referencia útil: para generar {formatear_euros(st.session_state['libertad_objetivo'])}/mes "
        f"en euros de hoy con la regla del 4%, haría falta aproximadamente un capital neto real de "
        f"{formatear_euros(capital_objetivo)}."
    )

    l1, l2 = st.columns(2)
    with l1:
        st.number_input(
            "Dinero deseado al mes (euros de hoy)",
            min_value=1.0,
            step=50.0,
            key="libertad_objetivo"
        )
    with l2:
        st.number_input(
            "Máximo de años a simular",
            min_value=1,
            max_value=100,
            step=1,
            key="libertad_max_años"
        )

    if st.button("Calcular años hasta libertad financiera"):
        try:
            texto = calcular_libertad_financiera()
            st.success("Cálculo realizado.")
            st.write(texto)
        except Exception as e:
            st.error(f"No se pudo hacer el cálculo inverso. Detalle: {e}")


# =========================================================
# TAB 5 - COMPARATIVA DE ACTIVOS
# =========================================================
with tabs[4]:
    st.subheader("COMPARATIVA DE ACTIVOS")
    st.write(
        "Tabla orientativa para ayudarte a no elegir la rentabilidad esperada completamente a ciegas.\n"
        "Son referencias educativas, no garantías futuras."
    )

    df_activos = pd.DataFrame(
        ACTIVOS,
        columns=["Activo", "Rentabilidad media orientativa (%)", "Volatilidad", "Comentario"]
    )
    st.dataframe(df_activos, use_container_width=True)

    opciones_activos = [a[0] for a in ACTIVOS]
    activo_seleccionado = st.selectbox("Selecciona un activo", opciones_activos)

    if st.button("Usar rentabilidad seleccionada en la simulación principal"):
        fila = next((a for a in ACTIVOS if a[0] == activo_seleccionado), None)
        if fila:
            st.session_state["rentabilidad_pendiente"] = float(fila[1])
            st.rerun()


# =========================================================
# TAB 6 - GUÍA EXCEL
# =========================================================
with tabs[5]:
    st.subheader("GUÍA DE COLUMNAS DEL EXCEL")
    st.write(
        "Esta pestaña explica qué significa cada columna que aparece en el Excel generado por la aplicación.\n"
        "También se exporta una hoja llamada 'Guía columnas' con esta misma información."
    )

    for nombre_columna, descripcion in GUIA_COLUMNAS_EXCEL.items():
        with st.container(border=True):
            st.markdown(f"**{nombre_columna}**")
            st.write(descripcion)
